KeenTools/keentools-blender

keentools_facebuilder/messages.py

OT-1615 update 1040 error text

---

keentools_facebuilder/fbloader.py
keentools_facebuilder/pinmode.py
keentools_facebuilder/settings.py
keentools_facebuilder/utils/other.py

missing keyframe exception handling
proper open files saved in pinmode

Ot 1630 OT 1631 keyframe exception and pinmode saved files open

---

keentools_facebuilder/fbloader.py
keentools_facebuilder/interface/panels.py
keentools_facebuilder/movepin.py
keentools_facebuilder/settings.py

Signed-off-by: Sergey Krivohatskiy <s.krivohatskiy@gmail.com>

OT-1692 auto rigidity removed

---

keentools_facebuilder/fbloader.py

Signed-off-by: Sergey Krivohatskiy <s.krivohatskiy@gmail.com>

Hotfix: expression_rigidity prop name fixed

---

keentools_facebuilder/interface/filedialog.py
keentools_facebuilder/main_operator.py
keentools_facebuilder/utils/blendshapes.py

also OT-1801 FACS animation button tooltips changing

OT-1802 Delete existing keys before animation loading

---

keentools_facebuilder/utils/blendshapes.py

OT-1803 Load only read FACSes instead of all

---

keentools_facebuilder/utils/operator_action.py

Forward and up axes predefined and Apply Transform options enabled

OT-1808 Change default FBX export settings 

---

keentools_facebuilder/config.py
keentools_facebuilder/interface/__init__.py
keentools_facebuilder/interface/menus.py
keentools_facebuilder/main_operator.py
keentools_facebuilder/movepin.py
keentools_facebuilder/settings.py
tests/integration_test.py
tests/test_utils.py

OT-1839 Rename pin settings controls

OT-1838 Add new integration tests

---

keentools_facebuilder/__init__.py
keentools_facebuilder/config.py
keentools_facebuilder/interface/panels.py
keentools_facebuilder/pick_operator.py
keentools_facebuilder/utils/edges.py
keentools_facebuilder/utils/shaders.py
keentools_facebuilder/viewport.py

OT-1856 Shader for rectangle drawing

---

keentools_facebuilder/interface/panels.py
keentools_facebuilder/movepin.py
keentools_facebuilder/settings.py

Maybe it should be renamed to ‘Minimize pins’ or something like that.

OT-1920 Add pin minimization to FaceBuilder

---

keentools_facebuilder/callbacks.py
keentools_facebuilder/config.py
keentools_facebuilder/fbloader.py
keentools_facebuilder/head.py
keentools_facebuilder/interface/filedialog.py
keentools_facebuilder/interface/panels.py
keentools_facebuilder/main_operator.py
keentools_facebuilder/movepin.py
keentools_facebuilder/pick_operator.py
keentools_facebuilder/pinmode.py
keentools_facebuilder/preferences/__init__.py
keentools_facebuilder/preferences/ui.py
keentools_facebuilder/preferences/user_preferences.py
keentools_facebuilder/settings.py
keentools_facebuilder/utils/cameras.py
keentools_facebuilder/utils/coords.py
keentools_facebuilder/utils/edges.py
keentools_facebuilder/utils/manipulate.py
keentools_facebuilder/utils/materials.py
keentools_facebuilder/utils/operator_action.py
keentools_facebuilder/utils/points.py
keentools_facebuilder/viewport.py
tests/test_utils.py

OT-1961 Fixes for localview bugs

---

README.md
keentools_facebuilder/__init__.py
keentools_facebuilder/blender_independent_packages/pykeentools_loader/config.py
keentools_facebuilder/config.py

Signed-off-by: Sergey Krivohatskiy <s.krivohatskiy@gmail.com>

Hotfix OT-2048 OT-2052 updaters and new LLF format

---

keentools_facebuilder/__init__.py
keentools_facebuilder/config.py
keentools_facebuilder/utils/edges.py
keentools_facebuilder/utils/images.py
keentools_facebuilder/utils/materials.py
tests/test_utils.py

OT-2287 Speed-up saving textures and changing wireframe.

---

keentools_facebuilder/pinmode.py
keentools_facebuilder/settings.py
keentools_facebuilder/utils/edges.py
keentools_facebuilder/utils/images.py
keentools_facebuilder/utils/materials.py
tests/test_utils.py

OT-2406 Undo-handler forces shaders update after undo call

OT-2411 Fix for pixels foreach getters and setters in old Blenders

---

README.md
keentools_facebuilder/__init__.py
keentools_facebuilder/blender_independent_packages/pykeentools_loader/config.py
keentools_facebuilder/config.py

Signed-off-by: Sergey Krivohatskiy <s.krivohatskiy@gmail.com>

Release 2022.1.1

---

keentools/facebuilder/fbloader.py
keentools/facebuilder/interface/panels.py
keentools/facebuilder/settings.py

Merge it to dev only after OT-2526 Improve UI for face model groups and transformations fixes

OT-2544 Change face locks UI

---

keentools/geotracker/camera_input.py
keentools/geotracker/gtloader.py
keentools/geotracker/interface/filedialogs.py
keentools/geotracker/movepin.py
keentools/geotracker/pinmode.py
keentools/geotracker/settings.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/utils/precalc.py
keentools/geotracker_config.py
keentools/utils/animation.py
keentools/utils/bpy_common.py
keentools/utils/rig_slider.py

Settings usage simplified. Better logging

OT-2682 Remove code not connected to new storage

---

keentools/facebuilder/callbacks.py
keentools/facebuilder/settings.py

Also added pins icon in model expression selector

OT-2724 Fix polygonality switching

---

keentools/addon_config.py
keentools/facebuilder/main_operator.py
keentools/facebuilder/pinmode.py
keentools/facebuilder/settings.py
keentools/facebuilder_config.py
keentools/geotracker/gtloader.py
keentools/geotracker/interface/filedialogs.py
keentools/geotracker/interface/panels.py
keentools/geotracker/operators.py
keentools/geotracker/pinmode.py
keentools/geotracker/settings.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/utils/precalc.py
keentools/geotracker_config.py
keentools/utils/animation.py
keentools/utils/blendshapes.py
keentools/utils/bpy_common.py
keentools/utils/images.py
keentools/utils/localview.py
keentools/utils/manipulate.py

OT-2812 Change gamma adjustment to exposure and gamma

---

keentools/geotracker/gtloader.py
keentools/geotracker/interface/panels.py
keentools/geotracker/movepin.py
keentools/geotracker/operators.py
keentools/geotracker/pinmode.py
keentools/geotracker/settings.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/viewport.py
keentools/geotracker_config.py
keentools/utils/points.py

OT-2471 Pin selection shading

---

keentools/addon_config.py
keentools/geotracker/gtloader.py
keentools/geotracker/movepin.py
keentools/geotracker/pinmode.py
keentools/geotracker/settings.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/utils/precalc.py
keentools/utils/images.py

Also hide GeoTracker depends on environment var

OT-2847 Precalc for video file without splitting

---

keentools/facebuilder/interface/panels.py
keentools/facebuilder/utils/edges.py
keentools/geotracker/__init__.py
keentools/geotracker/camera_input.py
keentools/geotracker/gtloader.py
keentools/geotracker/interface/__init__.py
keentools/geotracker/interface/filedialogs.py
keentools/geotracker/interface/panels.py
keentools/geotracker/operators.py
keentools/geotracker/pinmode.py
keentools/geotracker/settings.py
keentools/geotracker/utils/calc_timer.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/utils/precalc.py
keentools/geotracker/utils/textures.py
keentools/geotracker_config.py
keentools/utils/coords.py
keentools/utils/edges.py
keentools/utils/images.py
keentools/utils/kt_logging.py
keentools/utils/mesh_builder.py
keentools/utils/other.py
keentools/utils/ui_redraw.py
keentools/utils/warning.py
tests/gt_integration_test.py

And improved logging system via KTLogger

OT-2886 Texture reprojection sequence

---

keentools/facebuilder/interface/panels.py
keentools/geotracker/gtloader.py
keentools/geotracker/interface/panels.py
keentools/geotracker/movepin.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/utils/progress_callbacks.py
keentools/geotracker/utils/textures.py
keentools/geotracker/viewport.py
keentools/utils/bpy_common.py
keentools/utils/coords.py
keentools/utils/localview.py
keentools/utils/other.py

Refine progress indicator and pinmode escaper small refactoring

OT-2899 Improve camera projection by additional parameters

---

keentools/geotracker/movepin.py
keentools/geotracker_config.py
keentools/utils/blendshapes.py

One line fix: extend_scene_timeline_end(int(time)) 
and a lot of type hints

OT-2904 Fix CSV loading error while trying put float to scene frame_end

---

keentools/facebuilder/pinmode.py
keentools/facebuilder/settings.py
keentools/facebuilder/utils/edges.py
keentools/geotracker/gtloader.py
keentools/geotracker/interface/panels.py
keentools/geotracker/movepin.py
keentools/geotracker/pinmode.py
keentools/geotracker/settings.py
keentools/geotracker/utils/calc_timer.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker/utils/precalc.py
keentools/geotracker/utils/prechecks.py
keentools/geotracker/utils/textures.py
keentools/geotracker/viewport.py
keentools/utils/base_shaders.py
keentools/utils/bpy_common.py
keentools/utils/coords.py
keentools/utils/edges.py
keentools/utils/mesh_builder.py
keentools/utils/points.py
keentools/utils/polygons.py
keentools/utils/screen_text.py
keentools/utils/shaders.py
keentools/utils/viewport.py

and Toggle pins with selection

OT-2897 Show/Hide shaders by pressing tab

---

keentools/facebuilder/movepin.py
keentools/facebuilder/utils/edges.py
keentools/facebuilder_config.py
keentools/utils/base_shaders.py
keentools/utils/coords.py
keentools/utils/edges.py

glLineWidth parameter is explicitly defined in the base class

OT-3237 Shader classes refactoring

---

keentools/geotracker/gtloader.py
keentools/geotracker/interface/menus.py
keentools/geotracker/interface/panels.py
keentools/geotracker/operators.py
keentools/geotracker/ui_strings.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker_config.py

OT-3388 Clear tracking except keyframes

---

keentools/geotracker/interface/panels.py
keentools/geotracker/operators.py
keentools/geotracker/ui_strings.py
keentools/geotracker/utils/geotracker_acts.py
keentools/geotracker_config.py
keentools/utils/animation.py

And small UI changes in precalc settings

OT-3464 Bake animation in world coordinate system

---

keentools/addon_config.py
keentools/geotracker/pinmode.py
keentools/geotracker/utils/geotracker_acts.py
keentools/utils/coords.py
keentools/utils/points.py

and OT-3632 Sticky selection when interface is enlarged

OT-3633 GTB crashes on toggle pins
